/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/deepfabric/elasticell-operator/pkg/apis/deepfabric.com/v1alpha1"
	scheme "github.com/deepfabric/elasticell-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CellClustersGetter has a method to return a CellClusterInterface.
// A group's client should implement this interface.
type CellClustersGetter interface {
	CellClusters(namespace string) CellClusterInterface
}

// CellClusterInterface has methods to work with CellCluster resources.
type CellClusterInterface interface {
	Create(*v1alpha1.CellCluster) (*v1alpha1.CellCluster, error)
	Update(*v1alpha1.CellCluster) (*v1alpha1.CellCluster, error)
	UpdateStatus(*v1alpha1.CellCluster) (*v1alpha1.CellCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CellCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.CellClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CellCluster, err error)
	CellClusterExpansion
}

// cellClusters implements CellClusterInterface
type cellClusters struct {
	client rest.Interface
	ns     string
}

// newCellClusters returns a CellClusters
func newCellClusters(c *DeepfabricV1alpha1Client, namespace string) *cellClusters {
	return &cellClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cellCluster, and returns the corresponding cellCluster object, and an error if there is any.
func (c *cellClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.CellCluster, err error) {
	result = &v1alpha1.CellCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cellclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CellClusters that match those selectors.
func (c *cellClusters) List(opts v1.ListOptions) (result *v1alpha1.CellClusterList, err error) {
	result = &v1alpha1.CellClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cellclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cellClusters.
func (c *cellClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cellclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cellCluster and creates it.  Returns the server's representation of the cellCluster, and an error, if there is any.
func (c *cellClusters) Create(cellCluster *v1alpha1.CellCluster) (result *v1alpha1.CellCluster, err error) {
	result = &v1alpha1.CellCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cellclusters").
		Body(cellCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cellCluster and updates it. Returns the server's representation of the cellCluster, and an error, if there is any.
func (c *cellClusters) Update(cellCluster *v1alpha1.CellCluster) (result *v1alpha1.CellCluster, err error) {
	result = &v1alpha1.CellCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cellclusters").
		Name(cellCluster.Name).
		Body(cellCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cellClusters) UpdateStatus(cellCluster *v1alpha1.CellCluster) (result *v1alpha1.CellCluster, err error) {
	result = &v1alpha1.CellCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cellclusters").
		Name(cellCluster.Name).
		SubResource("status").
		Body(cellCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the cellCluster and deletes it. Returns an error if one occurs.
func (c *cellClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cellclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cellClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cellclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cellCluster.
func (c *cellClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CellCluster, err error) {
	result = &v1alpha1.CellCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cellclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
