apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-cell
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cell
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
{{ toYaml .Values.proxy.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if .Values.proxy.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.proxy.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: redis-client
    port: 4000
    targetPort: 4000
    protocol: TCP
    {{- if .Values.proxy.service.mysqlNodePort }}
    nodePort: {{ .Values.proxy.service.mysqlNodePort }}
    {{- end }}
  {{- if .Values.proxy.service.exposeStatus }}
  - name: status
    port: 10080
    targetPort: 10080
    protocol: TCP
    {{- if .Values.proxy.service.statusNodePort }}
    nodePort: {{ .Values.proxy.service.statusNodePort }}
    {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: proxy
