apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-proxy
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: proxy
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  startup-script: |-
{{ tuple "scripts/_start_proxy.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
