apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-store
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: store
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  startup-script: |-
{{ tuple "scripts/_start_store.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}

  config-file: |-
    {{- if .Values.store.config }}
{{ .Values.store.config | indent 4 }}
    {{- else }}
{{ tuple "config/_store-config.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
    {{- end -}}
