apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cellclusters.deepfabric.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: deepfabric.com
  # list of versions supported by this CustomResourceDefinition
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cellclusters
    # singular name to be used as an alias on the CLI and for display
    singular: cellcluster
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CellCluster
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cc
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            pd:
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                requests:
                  properties:
                    cpu:
                      type: string
            strore:
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                requests:
                  properties:
                    cpu:
                      type: string
            proxy:
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                requests:
                  properties:
                    cpu:
                      type: string
