/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/deepfabric/elasticell-operator/pkg/apis/deepfabric.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCellClusters implements CellClusterInterface
type FakeCellClusters struct {
	Fake *FakeDeepfabricV1alpha1
	ns   string
}

var cellclustersResource = schema.GroupVersionResource{Group: "deepfabric.com", Version: "v1alpha1", Resource: "cellclusters"}

var cellclustersKind = schema.GroupVersionKind{Group: "deepfabric.com", Version: "v1alpha1", Kind: "CellCluster"}

// Get takes name of the cellCluster, and returns the corresponding cellCluster object, and an error if there is any.
func (c *FakeCellClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.CellCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cellclustersResource, c.ns, name), &v1alpha1.CellCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CellCluster), err
}

// List takes label and field selectors, and returns the list of CellClusters that match those selectors.
func (c *FakeCellClusters) List(opts v1.ListOptions) (result *v1alpha1.CellClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cellclustersResource, cellclustersKind, c.ns, opts), &v1alpha1.CellClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CellClusterList{}
	for _, item := range obj.(*v1alpha1.CellClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cellClusters.
func (c *FakeCellClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cellclustersResource, c.ns, opts))

}

// Create takes the representation of a cellCluster and creates it.  Returns the server's representation of the cellCluster, and an error, if there is any.
func (c *FakeCellClusters) Create(cellCluster *v1alpha1.CellCluster) (result *v1alpha1.CellCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cellclustersResource, c.ns, cellCluster), &v1alpha1.CellCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CellCluster), err
}

// Update takes the representation of a cellCluster and updates it. Returns the server's representation of the cellCluster, and an error, if there is any.
func (c *FakeCellClusters) Update(cellCluster *v1alpha1.CellCluster) (result *v1alpha1.CellCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cellclustersResource, c.ns, cellCluster), &v1alpha1.CellCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CellCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCellClusters) UpdateStatus(cellCluster *v1alpha1.CellCluster) (*v1alpha1.CellCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cellclustersResource, "status", c.ns, cellCluster), &v1alpha1.CellCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CellCluster), err
}

// Delete takes name of the cellCluster and deletes it. Returns an error if one occurs.
func (c *FakeCellClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cellclustersResource, c.ns, name), &v1alpha1.CellCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCellClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cellclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CellClusterList{})
	return err
}

// Patch applies the patch and returns the patched cellCluster.
func (c *FakeCellClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CellCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cellclustersResource, c.ns, name, data, subresources...), &v1alpha1.CellCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CellCluster), err
}
