FROM alpine:3.5

RUN apk add tzdata --no-cache
ADD bin/cell-controller-manager /usr/local/bin/cell-controller-manager
ADD bin/cell-scheduler /usr/local/bin/cell-scheduler
ADD bin/cell-discovery /usr/local/bin/cell-discovery
